---

- name: Fail if not macOS
  fail:
    msg: Must be running macOS
  when:
    - ansible_os_family != 'Darwin'

- name: Register Homebrew install state
  stat:
    path: /usr/local/bin/brew
  register: homebrew_brew

- name: Fail if Homebrew is not installed
  fail:
    msg: No Homebrew at `/usr/local/bin/brew`
  when:
    - not homebrew_brew.stat.exists

- name: Update Homebrew
  homebrew: update_homebrew=yes upgrade_all=no

- name: Install Homebrew taps
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"

- name: Install Homebrew packages
  homebrew: "name={{ item }} state=present"
  with_items: "{{ homebrew_packages }}"

- name: Install Homebrew cask applications
  become_user: "{{ ansible_user_id }}"
  become: yes
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
    sudo_password: "{{ ansible_become_password }}"
  with_items: "{{ homebrew_casks }}"

- name: Log results
  template:
    src: homebrew.log.j2
    dest: $HOME/.shurroo/log/homebrew-{{ log_time }}.log
  when: write_log_file
  changed_when: false

- name: Register log status
  # Set to "log_no.txt" message in vars
  # Change to "log_yes.txt" message when write_log_file
  set_fact: log_status="log_yes.txt"
  when: write_log_file
  changed_when: false

- name: Register next steps
  # Set to "ready_no.txt" message in vars
  # Change to "ready_yes.txt" message when all conditions are met
  set_fact: next_steps="ready_yes.txt"
  when: true

- name: Next steps
  debug:
    msg: "{{ lookup('file', log_status, rstrip=false) }}{{ lookup('file', next_steps, rstrip=false) }}"

...
